micronaut:
    function:
        name: batch-scheduler
        version: 0.1
---
datasources:
    default:
        url: jdbc:h2:mem:default;INIT=runscript from 'classpath:init-db-schema.sql';DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password: ""
        driverClassName: org.h2.Driver